/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { animated, useSpring } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { Ketchup } from "./Ketchup";
import { Mustard } from "./Mustard";

export function HotDog(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/hot-dog/model.gltf");

  const {
    mustardPosition,
    ketchupPosition,
    ketchupRotationX,
    mustardRotationX,
    ketchupSauceScale,
    mustardSauceScale,
  } = useSpring({
    from: {
      ketchupPosition: [0.5, 0, 0],
      mustardPosition: [-0.5, 0, 0],
      ketchupSauceScale: 0,
      mustardSauceScale: 0,
      ketchupRotationX: 0,
      mustardRotationX: 0,
    },
    to: [
      {
        mustardRotationX: Math.PI,
        mustardPosition: [-0.5, 0.6, 0],
      },
      {
        mustardPosition: [0.3, 0.6, 0],
        mustardSauceScale: 2,
      },
      {
        mustardPosition: [-0.5, 0.6, 0],
      },
      {
        mustardRotationX: 0,
        mustardPosition: [-0.5, 0, 0],
      },
      {
        ketchupRotationX: Math.PI,
        ketchupPosition: [0.5, 0.6, 0],
      },
      {
        ketchupPosition: [-0.3, 0.6, 0],
        ketchupSauceScale: 2,
      },
      {
        ketchupPosition: [0.5, 0.6, 0],
      },
      {
        ketchupRotationX: 0,
        ketchupPosition: [0.5, 0, 0],
        ketchupSauceScale: 0,
        mustardSauceScale: 0,
      },
    ],
    config: {
      mass: 1,
      tension: 800,
      friction: 80,
    },
    loop: true,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.hotDog.geometry} material={materials.brownLight}>
        <group position={[0, 0.14, 0]} rotation={[Math.PI, 0, -Math.PI]}>
          <animated.mesh
            geometry={nodes.Mesh_sauce.geometry}
            material={materials.yellow}
            scale-y={mustardSauceScale}
            scale-z={mustardSauceScale}
          />
          <animated.mesh
            geometry={nodes.Mesh_sauce_1.geometry}
            material={materials.red}
            scale-y={ketchupSauceScale}
            scale-z={ketchupSauceScale}
          />
        </group>
        <mesh
          geometry={nodes.sausage.geometry}
          material={materials.brown}
          position={[-0.29, 0.09, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.93}
        />
      </mesh>
      <Ketchup rotation-x={ketchupRotationX} position={ketchupPosition} />
      <Mustard rotation-x={mustardRotationX} position={mustardPosition} />
    </group>
  );
}

useGLTF.preload("./models/hot-dog/model.gltf");
