/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { animated, config, useSpring } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

export function TargetStand(props) {
  const { posX } = useSpring({
    from: {
      posX: -0.5,
    },
    to: [
      {
        posX: 0.5,
      },
      { posX: -0.5 },
    ],
    config: config.stiff,
    loop: true,
  });

  const group = useRef();
  const { nodes, materials } = useGLTF("./models/target-stand/model.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <animated.group rotation={[Math.PI / 2, 0, 0]} position-x={posX}>
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={materials["Red.025"]}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={materials["White.025"]}
        />
        <mesh
          geometry={nodes.Cylinder016_2.geometry}
          material={materials["BrownDark.018"]}
        />
      </animated.group>
    </group>
  );
}

useGLTF.preload("./models/target-stand/model.gltf");
