/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

export function Fence(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/fence/model.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder095.geometry}
        material={materials["Black.011"]}
      />
      <mesh
        geometry={nodes.Cylinder095_1.geometry}
        material={materials["Stone.003"]}
      />
    </group>
  );
}

useGLTF.preload("./models/fence/model.gltf");
